mulesoft/mule-db-connector

src/main/java/org/mule/extension/db/internal/result/row/InsensitiveMapRowHandler.java
=> MULE-12606: Remove org.apache.commons from exported packages

src/main/java/org/mule/extension/db/internal/domain/connection/DbConnectionProvider.java
=> MULE-12608: Remove com.google.common from exported packages

pom.xml, src/test/java/org/mule/extension/db/integration/transaction/AbstractTxDbIntegrationTestCase.java
* move connector specific stuff to the corresponding connector
=> MULE-12255: Migrate testing namespaces to plugins

src/test/resources/integration/transaction/transactional-config.xml, src/test/resources/integration/xa/dynamic-xa-transactional-config.xml, src/test/resources/integration/xa/xa-transactional-config.xml
=> MULE-10223: Move MuleEventContext to compatibility module

src/test/java/org/mule/extension/db/integration/AbstractDbIntegrationTestCase.java, src/test/java/org/mule/extension/db/integration/AbstractQueryTimeoutTestCase.java, src/test/java/org/mule/extension/db/integration/ClobToString.java, src/test/java/org/mule/extension/db/integration/connectivity/DataSourcePoolingTestCase.java, src/test/java/org/mule/extension/db/integration/connectivity/StalePooledConnectionResetTestCase.java, src/test/java/org/mule/extension/db/integration/select/SelectTestCase.java, src/test/java/org/mule/extension/db/integration/streaming/DbStreamingTestCase.java
* Change security filter return type to 
* Remove some deprecated usages
* Event interface split
=> MULE-13363: Allow access to session properties from privileged API

src/test/java/org/mule/extension/db/integration/AbstractDbIntegrationTestCase.java
=> MULE-12716: Remove registries from API

src/test/java/org/mule/extension/db/integration/connectivity/DataSourcePoolingTestCase.java
=> MULE-13700: Implement flow stack dump

src/main/java/org/mule/extension/db/api/param/BulkQueryDefinition.java, src/main/java/org/mule/extension/db/internal/operation/BulkOperations.java
(cherry picked from commit 9b2a284e5f7b7e84343ec7bd0ab043ea7e546109)
=> MULE-16400: Revert parameter order (#157)

src/main/java/org/mule/extension/db/internal/operation/DmlOperations.java, src/test/java/org/mule/extension/db/integration/select/SelectTestCase.java, src/test/resources/integration/select/select-config.xml
Reverts mulesoft/mule-db-connector#177
=> Revert "MULE-17005: DB connections are not released when using "General Connection" configuration."

pom.xml, src/test/java/org/mule/extension/db/integration/DbArtifactClassLoaderRunnerConfig.java
MULE-18133: Get Oracle driver from maven central to run tests on Oracle DB
=> MULE-18133: Get Oracle driver from maven central to run tests on Oracle DB

src/main/java/org/mule/extension/db/internal/domain/executor/BulkUpdateExecutor.java
=> Applied parameterized logging (#287)

src/main/java/org/mule/extension/db/internal/operation/DmlOperations.java, src/test/java/org/mule/extension/db/integration/storedprocedure/StoredProcedureReturningConnectionTestCase.java, src/test/resources/integration/config/derby-datasource.xml, src/test/resources/integration/config/mssql-db-config.xml, src/test/resources/integration/config/mysql-db-config.xml, src/test/resources/integration/config/oracle-db-config.xml, src/test/resources/integration/storedprocedure/stored-procedure-returning-connections.xml
… is returned (#298)
* fix/DBCON-225: updates test name
=> DBCON-225: Stored Procedure does not close connections when no stream is returned

pom.xml
Co-authored-by: Engineering Services Bot <engineering-services-bot@mulesoft.com>
=> Update dependency io.fabric8:docker-maven-plugin to v0.34.1 (#300)

src/main/java/org/mule/extension/db/internal/result/row/NonStreamingInsensitiveMapRowHandler.java, src/main/java/org/mule/extension/db/internal/source/RowListener.java, src/test/java/org/mule/extension/db/integration/source/RowListenerTestCase.java, src/test/resources/integration/source/row-listener-config.xml
…s (#329)
* fix/DBCON-234: logging formatting
=> DBCON-234: On Table Row Listener does not allow consumption of Streams

src/main/java/org/mule/extension/db/internal/result/resultset/ResultSetIterator.java, src/test/java/org/mule/extension/db/unit/ResultSetIteratorTestCase.java
* Throw ModuleException in ResultSetIterator
* Reformated the test class
=> Throw a ModuleException instead of NoSuchElementException (#358)

pom.xml
=> Revert "Update dependency mysql:mysql-connector-java to v8 (#353)"

Jenkinsfile-mssql, Jenkinsfile-mysql, Jenkinsfile-mysql-old-version, Jenkinsfile-oracle, build-mssql.yaml, build-mysql-old-version.yaml, build-mysql.yaml, build-oracle.yaml, src/test/java/org/mule/extension/db/integration/source/RowListenerTestCase.java
(cherry picked from commit a24392820a2ff1c5d23dd42016b2f47791d06dc4)
=> DEL-1822: Fix builds using a custom Jenkinsfile (#344)

pom.xml
=> COCO-50-1.10.x: upgraded core-modules-parent to 1.1.9 

pom.xml
This release only includes a backward-incompatibility fix
=> Releasing 1.11.1 (includes DBCLI-25)

pom.xml
=> MMP-597: Shader version 1.0.2 breaks compatibility when used in connectors.

pom.xml, src/test/munit/oracle/arrays-and-structs-oracle-test-case.xml
Added tests for prepareArray and prepareStruct and depend on a released db-client supporting these new DW functions.
=> W-10673234: Added prepareArray and prepareStruct (via db-client)

pom.xml
Upgrade db-client version to 1.5.1, which contains a fix for W-10673234 fix.
=> W-10673234: Upgrade dbclient to 1.5.1

src/test/java/org/mule/extension/db/internal/OracleCreateArrayTestCase.java, src/test/java/org/mule/extension/db/internal/OracleCreateStructTestCase.java
Update class name and remove non-Oracle test cases for DB-connector
=> [W-11147791] Update class name and remove non-Oracle test cases for DB-connector

pom.xml
=> W-11755478_W-11762357-1.13.x: update DB client version

pom.xml
W-11755478_W-11762357 release 1.13.8
=> Chore/W-11755478_W-11762357 release 1.13.8

pom.xml, src/main/java/org/mule/extension/db/internal/domain/connection/datasource/DbDataSourceReferenceConnectionProvider.java, src/main/java/org/mule/extension/db/internal/domain/connection/derby/DerbyConnection.java, src/main/java/org/mule/extension/db/internal/domain/connection/derby/DerbyConnectionProvider.java, src/main/java/org/mule/extension/db/internal/domain/connection/generic/DbGenericConnectionProvider.java, src/main/java/org/mule/extension/db/internal/domain/connection/oracle/OracleDbConnection.java, src/main/java/org/mule/extension/db/internal/domain/connection/oracle/OracleDbConnectionProvider.java, src/main/java/org/mule/extension/db/internal/domain/connection/sqlserver/SqlServerConnection.java, src/main/java/org/mule/extension/db/internal/domain/connection/sqlserver/SqlServerConnectionProvider.java, src/main/java/org/mule/extension/db/internal/source/RowListener.java, src/test/java/org/mule/extension/db/internal/AbstractDbFunctionTestCase.java, src/test/java/org/mule/extension/db/internal/OracleCreateArrayTestCase.java, src/test/java/org/mule/extension/db/internal/OracleCreateStructTestCase.java, src/test/java/org/mule/extension/db/internal/domain/connection/OracleDbConnectionTestCase.java
*Hi, thank you for your work. We understand that you want to merge your changes and move on from this issue, but we also want to maintain the safety, readability, and testability of our code. Because of this, we kindly ask that you confirm that you have fulfilled the prerequisites for each category of activity before merging your changes.*
**NOTE**: *The release process ends when you merge the pull request that updates the support branch to the new snapshot, please don't forget to do this.*
=> [W-12167736] parameterization of template cache size

pom.xml, src/main/java/org/mule/extension/db/internal/domain/connection/datasource/DbDataSourceReferenceConnectionProvider.java, src/main/java/org/mule/extension/db/internal/domain/connection/derby/DerbyConnection.java, src/main/java/org/mule/extension/db/internal/domain/connection/derby/DerbyConnectionProvider.java, src/main/java/org/mule/extension/db/internal/domain/connection/generic/DbGenericConnectionProvider.java, src/main/java/org/mule/extension/db/internal/domain/connection/oracle/OracleDbConnection.java, src/main/java/org/mule/extension/db/internal/domain/connection/oracle/OracleDbConnectionProvider.java, src/main/java/org/mule/extension/db/internal/domain/connection/sqlserver/SqlServerConnection.java, src/main/java/org/mule/extension/db/internal/domain/connection/sqlserver/SqlServerConnectionProvider.java, src/main/java/org/mule/extension/db/internal/source/RowListener.java, src/test/java/org/mule/extension/db/internal/AbstractDbFunctionTestCase.java, src/test/java/org/mule/extension/db/internal/OracleCreateArrayTestCase.java, src/test/java/org/mule/extension/db/internal/OracleCreateStructTestCase.java, src/test/java/org/mule/extension/db/internal/domain/connection/OracleDbConnectionTestCase.java
*Hi, thank you for your work. We understand that you want to merge your changes and move on from this issue, but we also want to maintain the safety, readability, and testability of our code. Because of this, we kindly ask that you confirm that you have fulfilled the prerequisites for each category of activity before merging your changes.*
**NOTE**: *The release process ends when you merge the pull request that updates the support branch to the new snapshot, please don't forget to do this.*
=> [W-12167736] parameterisation of template cache size

pom.xml
*Hi, thank you for your work. We understand that you want to merge your changes and move on from this issue, but we also want to maintain the safety, readability, and testability of our code. Because of this, we kindly ask that you confirm that you have fulfilled the prerequisites for each category of activity before merging your changes.*
**NOTE**: *The release process ends when you merge the pull request that updates the support branch to the new snapshot, please don't forget to do this.*
=> [W-12167736] release 1.14.0

pom.xml
_Hi, thank you for your work. We understand that you want to merge your changes and move on from this issue, but we also want to maintain the safety, readability, and testability of our code. Because of this, we kindly ask that you confirm that you have fulfilled the prerequisites for each category of activity before merging your changes._
=> W-12545854: added process value output condition to BLOB values
